---
title: "Last proyect"
author: "Joseba"
date: "11/1/2022"
output:
  rmdformats::downcute:
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: false
    highlight: tango
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(combinat)
library(GGally)
```
```{r}
df <- read.csv(file ='/home/joseba/Master/Master-git/DataVis/Resampling Methods/proyecto/data_waves/fourth/madrid_fourth.csv')

casos <- df$num_casos
temperatura <- df$tmed
precip <- df$prec
statistical_column <- c("num_casos","tmed","wind","prec")

print (ks.test(df$num_casos, "pnorm", mean=mean(df$num_casos), sd=sd(df$num_casos)))
print (ks.test(df$tmed, "pnorm", mean=mean(df$tmed), sd=sd(df$tmed)))
print (ks.test(df$wind, "pnorm", mean=mean(df$wind), sd=sd(df$wind)))
print (ks.test(df$prec, "pnorm", mean=mean(df$prec), sd=sd(df$prec)))

hist(df$num_casos)

```

Now we can calculate the spearman correlation test:

```{r}
provinces <- c('alava', 'albacete', 'alicante', 'almeria', 'asturias', 'avila',
       'badajoz', 'baleares', 'barcelona', 'bizkaia', 'burgos', 'caceres',
       'cadiz', 'cantabria', 'castellon', 'ceuta', 'ciudadReal', 'cordoba',
       'coruña', 'cuenca', 'gipuzkoa', 'girona', 'granada', 'guadalajara',
       'huelva', 'huesca', 'jaen', 'laRioja', 'lasPalmas', 'leon', 'lleida',
       'lugo', 'madrid', 'malaga', 'melilla', 'murcia', 'navarra', 'ourense',
       'palencia', 'pontevedra', 'salamanca', 'santaCruzDeTenerife', 'segovia',
       'sevilla', 'soria', 'tarragona', 'teruel', 'toledo', 'valencia',
       'valladolid', 'zamora', 'zaragoza')
waves <- c("first","second","third","fourth","fifth")
path0 <- "/home/joseba/Master/Master-git/DataVis/Resampling Methods/proyecto/data_waves"


provincias_vec <- c()
wave_vec <- c()

correlation_vec_temp <- c()
p_value_vec_temp <- c()

correlation_vec_wind <- c()
p_value_vec_wind <- c()

correlation_vec_prec <- c()
p_value_vec_prec <- c()

temperature_vec <- c()

for (wave in waves){
  path <- paste0(path0,"/",wave)
  for (province in provinces){
    path <- paste0(path,"/",province,"_",wave,".csv")
    df <- read.csv(file = path)
    
    casos <- df$num_casos
    temperatura <- df$tmed
    viento <- df$wind
    precip <- df$prec
   
    path <- paste0(path0,"/",wave)
    
    #fill vectors
    provincias_vec <- append(provincias_vec, province, after = length(provincias_vec))
    wave_vec<-append(wave_vec, wave, after = length(wave_vec))
    
    #temp 
    sttrue= cor.test(casos,temperatura, method = "spearman", exact=FALSE)
    correlation_vec_temp<-append(correlation_vec_temp, sttrue[[4]], after = length(correlation_vec_temp))
    p_value_vec_temp<-append(p_value_vec_temp, sttrue[[3]], after = length(p_value_vec_temp))

    #wind
    sttrue= cor.test(casos,viento, method = "spearman", exact=FALSE)
    correlation_vec_wind<-append(correlation_vec_wind, sttrue[[4]], after = length(correlation_vec_wind))
    p_value_vec_wind<-append(p_value_vec_wind, sttrue[[3]], after = length(p_value_vec_wind))

    #prec
    sttrue= cor.test(casos,precip, method = "spearman", exact=FALSE)
    correlation_vec_prec<-append(correlation_vec_prec, sttrue[[4]], after = length(correlation_vec_prec))
    p_value_vec_prec<-append(p_value_vec_prec, sttrue[[3]], after = length(p_value_vec_prec))
    
    }
}

DataFrame.correlations <- data.frame(provincias_vec,wave_vec,
                                      correlation_vec_temp,p_value_vec_temp,correlation_vec_wind,p_value_vec_wind, correlation_vec_prec,p_value_vec_prec)    

write.csv(DataFrame.correlations,"/home/joseba/Master/Master-git/DataVis/Resampling Methods/proyecto/R/Spearman.csv", row.names = FALSE)
```
## Correlation Plot

```{r}

path <- '/home/joseba/Master/Master-git/DataVis/Resampling Methods/proyecto/data_waves/second/jaen_second.csv'
df <- read.csv(file = path)

casos <- df$num_casos
temperatura <- df$tmed
precip <- df$prec
viento <- df$wind


fit1 <- lm(casos ~ temperatura + precip + viento, data = df)
summary(fit1)
```

```{r}
library(ggplot2)

ggplot(df, aes(x = temperatura + precip + viento, y = casos)) + 

  geom_point() +
  stat_smooth(method = "lm", col = "blue")
```

